fix query for 5xx alert

diff --git a/pipeline/templates/terragrunt_job.yml b/pipeline/templates/terragrunt_job.yml
--- a/pipeline/templates/terragrunt_job.yml
+++ b/pipeline/templates/terragrunt_job.yml
@@ -74,9 +74,10 @@ jobs:
           # Get variable group id
           variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"
 
-          echo "########## DEBUG ############"
-          echo "variable group id: $variableGroupId"
-
+          if [ -z $variableGroupId ]; then
+            echo "Variable group ${{ parameters.variableGroupName }} was not found."
+            exit 1
+          fi
 
           VARS_FILE=terraform.tfvars.json
           echo "Writing variables to $VARS_FILE..."
