rm duplicated jq check. Update conditional step format (#208)

diff --git a/pipeline/templates/terragrunt_job.yml b/pipeline/templates/terragrunt_job.yml
--- a/pipeline/templates/terragrunt_job.yml
+++ b/pipeline/templates/terragrunt_job.yml
@@ -121,48 +121,41 @@ jobs:
             echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
             echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
 
-      - bash: |
-          # Ensure jq
-          if ! command -v jq &> /dev/null; then
-            echo "Installing jq..."
-            sudo apt update
-            sudo apt install -y jq
-          fi
+      - ${{ if ne(parameters.variableGroupName, '') }}:
+          - bash: |
+              echo "Configuring az devops cli..."
+              az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
 
-          echo "Configuring az devops cli..."
-          az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
+              echo "Retrieving variables from variable group ${{ parameters.variableGroupName }}..."
 
-          echo "Retrieving variables from variable group ${{ parameters.variableGroupName }}..."
+              # Get variable group id
+              variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"
 
-          # Get variable group id
-          variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"
+              if [ -z $variableGroupId ]; then
+                echo "Variable group ${{ parameters.variableGroupName }} was not found."
+                exit 1
+              fi
 
-          if [ -z $variableGroupId ]; then
-            echo "Variable group ${{ parameters.variableGroupName }} was not found."
-            exit 1
-          fi
+              VARS_FILE=terraform.tfvars.json
+              echo "Writing variables to $VARS_FILE..."
 
-          VARS_FILE=terraform.tfvars.json
-          echo "Writing variables to $VARS_FILE..."
+              # Write all variables in the group to a file
+              az pipelines variable-group variable list --group-id $variableGroupId > vars.json
 
-          # Write all variables in the group to a file
-          az pipelines variable-group variable list --group-id $variableGroupId > vars.json
+              # Write tfvars file
+              jq 'map_values(.value)' vars.json > "$VARS_FILE"
 
-          # Write tfvars file
-          jq 'map_values(.value)' vars.json > "$VARS_FILE"
-
-          if [ -f "$VARS_FILE" ]; then
-            echo "File $VARS_FILE has been written to $(moduleDir). It will be automatically consumed by terraform."
-            exit 0
-          else
-            echo "File $VARS_FILE not found."
-            exit 1
-          fi
-        displayName: "Write tfvars file from variable group"
-        condition: ${{ ne(parameters.variableGroupName, '') }}
-        workingDirectory: $(moduleDir)
-        env:
-          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
+              if [ -f "$VARS_FILE" ]; then
+                echo "File $VARS_FILE has been written to $(moduleDir). It will be automatically consumed by terraform."
+                exit 0
+              else
+                echo "File $VARS_FILE not found."
+                exit 1
+              fi
+            displayName: "Write tfvars file from variable group"
+            workingDirectory: $(moduleDir)
+            env:
+              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
 
       - bash: |
           PLAN_PATH='$(moduleDir)/tf.plan'
@@ -183,7 +176,8 @@ jobs:
             displayName: "!!! ${{parameters.environment}} Apply ${{parameters.module}} !!!"
             workingDirectory: $(moduleDir)
 
-      - bash: |
-          rm -f vars.json terraform.tfvars.json
-        displayName: "Delete sensitive variable files"
-        workingDirectory: $(moduleDir)
+      - ${{ if ne(parameters.variableGroupName, '') }}:
+          - bash: |
+              rm -f vars.json terraform.tfvars.json
+            displayName: "Delete sensitive variable files"
+            workingDirectory: $(moduleDir)
