test

diff --git a/pipeline/tag-test.yml b/pipeline/tag-test.yml
--- a/pipeline/tag-test.yml
+++ b/pipeline/tag-test.yml
@@ -16,43 +16,41 @@ steps:
   - checkout: self
     persistCredentials: true
 
-  # - script: |
-  #     set -euo pipefail
-
-  #     newTag="v$(releaseVersion)"
-
-  #     latestTag=$(git ls-remote --tags origin 'refs/tags/v*' |
-  #       awk '{sub("refs/tags/", "", $2); print $2}' |
-  #       sort -V |
-  #       tail -n 1)
-
-  #     echo "Latest tag: $latestTag"
-
-  #     if [[ "$latestTag" == "$newTag" ]]; then
-  #       echo "##vso[task.logissue type=error]The repository is already tagged with version $newTag. Please bump the releaseVersion variable."
-  #       exit 1
-  #     elif [[ "$(printf '%s\n%s\n' "$latestTag" "$newTag" | sort -V | tail -n1)" == "$latestTag" ]]; then
-  #       echo "##vso[task.logissue type=error]The semver value of variable releaseVersion ($(releaseVersion)) must be higher than ${latestTag#v}."
-  #       exit 1
-  #     else
-  #       echo "On merge, the respository will be tagged with a new release version $newTag"
-  #     fi
-  #   displayName: "Validate releaseVersion variable"
-
-  - script:
+  - script: |
       set -euo pipefail
 
-      echo "Local tags:"
-      git tag
-
-      echo "Remote tags:"
-      git ls-remote --tags --refs origin
+      if [[ ! "$(releaseVersion)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        echo "##vso[task.logissue type=error]The value of \$(releaseVersion) ($(releaseVersion)) is not a valid semantic version. Expected format: MAJOR.MINOR.PATCH."
+        exit 1
+      fi
 
       newTag="v$(releaseVersion)"
 
-      git tag -f $newTag
+      # get all tags from origin and sort by version (ignore annotated tags peeled references)
+      latestTag=$(git ls-remote --tags origin 'refs/tags/v*' |
+        awk '$2 !~ /\^\{\}$/ {sub("refs/tags/", "", $2); print $2}' |
+        sort -V |
+        tail -n 1)
 
-      git push origin refs/tags/$newTag
+      echo "Latest tag: $latestTag"
+      echo "New tag: $newTag"
+
+      if [[ "$(printf '%s\n%s\n' "$latestTag" "$newTag" | sort -V | tail -n1)" <= "$latestTag" ]]; then
+        echo "##vso[task.logissue type=error]The semver value of \$(releaseVersion) ($(releaseVersion)) must be greater than ${latestTag#v}."
+        exit 1
+      else
+        echo "On merge, the respository will be tagged with a new release version $newTag"
+        echo "##vso[task.setvariable variable=newTag;]$newTag"
+      fi
+    displayName: "Validate releaseVersion variable"
+
+  - script: |
+      set -euo pipefail
+
+      # overwrite any local tags. We are only interested in the remote
+      git tag -f $(newTag)
+
+      git push origin refs/tags/$(newTag)
     # only tag repo on merge to main
-    condition: and(succeeded(), eq(variables.buildReason, 'Manual'))
+    condition: and(succeeded(), eq(variables.buildReason, 'IndividualCI'))
     displayName: "Tag repo"
